name: Delete Suspended Inactive JumpCloud Users

on:
  # schedule:
  #commenting out until manual test works  - cron: '0 14 * * 1'  # Every Monday at 7:00 AM PST, but it will check if it is the first Monday or not
  workflow_dispatch: #Allow manual run

jobs:
  delete-users:
    runs-on: ubuntu-latest

    steps:
      - name: Check if today is the first Monday
        run: |
          day=$(date +%d)
          weekday=$(date +%u) # Monday = 1
          if [ "$day" -le 7 ] && [ "$weekday" -eq 1 ]; then
            echo "✅ First Monday detected. Proceeding."
          else
            echo "⏭️ Not the first Monday. Exiting."
            exit 0
          fi

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run deletion script
        run: python delete_users.py
        env:
          JC_API_KEY: ${{ secrets.JC_API_KEY }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
