name: Delete JumpCloud Users

on:
  schedule:
    - cron: '0 14 * * 1' # Every Monday at 14:00 UTC
  workflow_dispatch: # Allow manual run

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run deletion script
        env:
          JUMPCLOUD_API_KEY: ${{ secrets.JUMPCLOUD_API_KEY }}
          DND_GROUP_ID: ${{ secrets.DND_GROUP_ID }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: python delete_users.py